{
  "hash": "025911ec7604baa7bd1c608b104d8740",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Welcome to MAT 212!\"\nauthor: \"Prof. Eric Friedlander\"\ndate: \"2024-08-28\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 MAT 212 - Fall 2024 -  Schedule](https://mat212fa24.netlify.app/schedule)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\n---\n\n\n# Welcome!\n\n## Meet Prof. Friedlander! {.midi}\n\n::: incremental\n-   Education and career journey\n    -   BS in Math & Statistics from Rice University (Houston, TX)\n    -   Business Analyst at Capital One (Plano, TX)\n    -   MS and PhD in Statistics & Operations Research from UNC-Chapel Hill\n    -   Postdoc in Population Genetics at University of Chicago\n    -   Assistant Professor of Math at St. Norbert College (Green Bay, WI)\n-   Work focuses on statistics education, queueing theory, and population genetics\n-   Dad of three cute dogs\n    -   Insert dog pics\n:::\n\n<!-- ## Meet the Teaching Assistants (TAs) -->\n\n<!-- -   Sam Rosen (PhD): Head TA + Lab 01 -->\n\n<!-- -   Bethany Astor (MS): Lab 02 -->\n\n<!-- -   Jon Campbell (MS) -->\n\n<!-- -   Donald Cayton (MS): Lab 02 -->\n\n<!-- -   Allison Li (UG) -->\n\n<!-- -   Mitchelle Mojekwu (UG): Lab 04 -->\n\n<!-- -   Ben Thorpe (UG) -->\n\n<!-- -   Linxuan Wang (MS): Lab 03 -->\n\n<!-- -   Xiaojun Zheng (PhD): Lab 04 -->\n\n<!-- # Check-in on Ed Discussion! -->\n\n<!-- Click on the link and answer the Ed Discussion poll -->\n\n<!-- -   [Section 001 (10:05am lecture)](https://edstem.org/us/courses/44523/discussion/3346720) -->\n\n<!-- -   [Section 002 (1:25pm lecture)](https://edstem.org/us/courses/44523/discussion/3346722) -->\n\n# Statistical modeling\n\n## What is a model?\n\n:::{.incremental}\n- DATA = MODEL + ERROR\n- DATA = PATTERN + DEPARTURES FROM PATTERN\n  - How do we identify the actual pattern?\n- **GOAL:** Find a model for a relationship between a **response/outcome/target variable** $Y$ and one (or more) **explanatory/predictor variables** ($X_1,\\ldots,X_k$)\n- Models are a simplified but tractable version of reality\n:::\n\n## Geoge E. P. Box\n\n::::{.columns}\n:::{.column}\n- From wikipedia: British statistician, who worked in the areas of quality control, time-series analysis, design of experiments, and Bayesian inference. He has been called \"one of the great statistical minds of the 20th century\".\n- \"all models are wrong, but some are useful\"\n:::\n:::{.column}\n![](images/01/GeorgeEPBox.jpg)\n:::\n::::\n\n## Why build a model?\n\n1. Making predictions\n2. Understanding relationships\n3. Assessing differences\n\n# Some Review\n\n## Types of Variables\n\n- *Quantitative/Numerical:* expressible as numbers for which arithmetic makes sense\n- *Categorical:* divides sample points into groups\n  + *Binary* = categorical with just two groups\n- *Note:* Just because a variable is coded using a number doesn't automatically make it quantitative\n\n## Course Overview\n\n|**Chapter** | **Response** | **Predictor/Explanatory** |\n|:------------:|--------------|------------------|\n|1-2      | Quantitative | Single Quantitative|\n|3-4      | Quantitative | Multiple Quantitative|\n|5      | Quantitative | Single Categorical|\n|6-8      | Quantitative | Multiple Categorical|\n|9     | Categorical | Single Quant/Cat|\n|10     | Categorical | Multiple Quant/Cat|\n|11     | Both | Both|\n\n\n## Types of Studies\n\n\n:::{.incremental}\n- **Observational study:** Data recorded without \"manipulating\" any of the variables.\n- **Experiment:** One or more of the explanatory variables is/are assigned/controlled for all experimental units.\n- Should use an experiment to confirm a “cause/effect” relationship.\n:::\n\n## Building a Statistical Model: Four-Step Process\n\n1. **Choose:** Pick a form for the model.\n2. **Fit:** Estimate any parameters.\n3. **Assess:** Is the model adequate? Could it be simpler? Are conditions met?\n4. **Use:** Answer the question of interest.\n\n## General Form of a Model\n\n:::{.center}\n> $Y = \\underbrace{f(X)}_{\\text{Expected } Y \\text{ for some} \\\\ \\text{combination of} \\\\ \\text{predictors}} + \\underbrace{\\epsilon}_{\\text{Random} \\\\    \\text{Error}}$\n:::\n\n- DATA = MODEL + ERROR\n\n## Example: Bike Commute {.smaller}\n\n- [Data](https://cran.r-project.org/web/packages/Lock5Data/Lock5Data.pdf) from a [study](https://www.bmj.com/content/341/bmj.c6801) called ``Bicycle weight and commuting time: randomised trial''which appeared in the British Medical Journal in 2010\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) # Lots of helpful functions\nlibrary(mosaic) # Lots of helpful functions\nlibrary(Lock5Data) # contains the data\nhead(BikeCommute) # shows us the first six rows of data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Bike     Date Distance    Time Minutes AvgSpeed TopSpeed Seconds Month\n1  Steel 20/01/10    27.20 1:55:04  115.07    14.10    31.50    6904  1Jan\n2 Carbon 21/01/10    27.46 1:55:35  115.58    14.25    30.64    6935  1Jan\n3  Steel 25/01/10    27.20 1:55:45  115.75    14.10    30.92    6945  1Jan\n4 Carbon 26/01/10    27.52 1:53:56  113.93    14.49    33.02    6836  1Jan\n5 Carbon 27/01/10    27.51 1:59:12  119.20    13.84    30.92    7152  2Feb\n6  Steel 01/02/10    27.17 1:48:44  108.73    14.99    32.09    6524  2Feb\n```\n\n\n:::\n:::\n\n\n- Target Variable: `AvgSpeed`\n\n## `AvgSpeed` Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~AvgSpeed, data = BikeCommute, bins = 10)\n```\n\n::: {.cell-output-display}\n![](01-welcome_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n## Example: Constant Model\n\n- $Y = \\mu + \\epsilon$\n  + $\\mu$ is just an (unknown) constant\n- *Terminology:*\n  + $\\mu$ is called a *parameter* of the model\n  + Use data to provide a *sample estimate* of $\\mu$\n  + Estimates of parameters get little \"hats\", i.e. $\\hat{\\mu}$ is an estimate of $\\mu$\n\n. . .\n\n- How should we estimate $\\mu$?\n\n## Estimating $\\mu$ {.smaller}\n\n::::{.columns}\n:::{.column}\n- Estimate $\\mu$ using the sample mean\n  + $\\hat{\\mu} = \\bar{y}$\n- Estiamte $\\mu$ using the sample median\n  + $\\hat{\\mu} = m$\n:::\n:::{.column}\n\n::: {.cell}\n\n```{.r .cell-code}\nBikeCommute |> \n  summarize(sample_mean = mean(AvgSpeed),\n            sample_median = median(AvgSpeed)) # Using the Tidyverse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sample_mean sample_median\n1    15.10571        15.045\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(BikeCommute$sample_mean) # Using Base-R\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(BikeCommute$sample_median)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n:::\n\n:::\n::::\n\n## Predicted Value for Response\n\n- Estimate $Y$ using the model with estimated parameters.\n- The predicted y is denoted... [ $\\hat{y}$ ]{.fragment .fade-in}\n\n:::{.fragment}\n\n- For the constant model $\\hat{y} = \\hat{\\mu}$\n- Examples:\n  + $\\hat{y} = \\bar{y} = 15.106$ (sample mean)\n  + $\\hat{y} = m = 15.045$ (sample median)\n  \n:::\n\n## Visualizing the Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~AvgSpeed, data = BikeCommute, bins = 10) |> \n  gf_vline(xintercept = 15.106, color = \"red\") |> \n  gf_vline(xintercept = 15.045, color = \"blue\")\n```\n\n::: {.cell-output-display}\n![](01-welcome_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n  \n## Is our model good?\n\n1. Which estimator (mean or median) is better? That is, how can we compare models?\n2. Is either model any good? That is, how can we assess fit?\n\n## Residuals\n\n- **Residual:** actual value (from data) minus predicted value (from model)\n  + Can compute the residual for every observation in our data\n\n> $$\\text{Residual} = \\underbrace{y}_{Actual} - \\underbrace{\\hat{y}}_{Predicted}$$\n\n## Visualizing Residuals {.smaller}\n\n- Consider the sample mean model\n- Say we want to make a prediction for the first observation in our data set\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_histogram(~AvgSpeed, data = BikeCommute, bins = 10) |> \n  gf_vline(xintercept = 15.106, color = \"red\") |> \n  gf_vline(xintercept = BikeCommute$AvgSpeed[1], color = \"green\")\n```\n\n::: {.cell-output-display}\n![](01-welcome_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n - Where is the residual in this picture?\n\n  \n## Criteria to Minimize Residuals\n\n- Sum of Residuals: $\\sum_{i=1}^n(y_i-\\hat{y}_i)$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBikeCommute |> \n  summarize(sample_mean = mean(AvgSpeed),\n            sample_median = median(AvgSpeed),\n            sample_mean_sum = sum(AvgSpeed - sample_mean),\n            sample_median_sum = sum(AvgSpeed - sample_median))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sample_mean sample_median sample_mean_sum sample_median_sum\n1    15.10571        15.045    4.085621e-14               3.4\n```\n\n\n:::\n:::\n\n\n- Sum isn't helpful: Residuals can be negative!\n\n## Criteria to Minimize Residuals {.smaller}\n\n- Sum of absolute deviations: $\\sum_{i=1}^n |y_i-\\hat{y}_i|$\n- Sum of squared errors: $\\sum_{i=1}^n (y_i-\\hat{y}_i)^1$\n\n## Sum of absolute deviations\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBikeCommute |> \n  summarize(sample_mean = mean(AvgSpeed),\n            sample_median = median(AvgSpeed),\n            sample_mean_abs_sum = sum(abs(AvgSpeed - sample_mean)),\n            sample_median_abs_sum = sum(abs(AvgSpeed - sample_median)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sample_mean sample_median sample_mean_abs_sum sample_median_abs_sum\n1    15.10571        15.045            33.75143                 33.74\n```\n\n\n:::\n:::\n\n\n- Which model is better?\n\n## Sum of squared errors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBikeCommute |> \n  summarize(sample_mean = mean(AvgSpeed),\n            sample_median = median(AvgSpeed),\n            sample_mean_sq_sum = sum((AvgSpeed - sample_mean)^2),\n            sample_median_sq_sum = sum((AvgSpeed - sample_median)^2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sample_mean sample_median sample_mean_sq_sum sample_median_sq_sum\n1    15.10571        15.045           28.82357                29.03\n```\n\n\n:::\n:::\n\n\n- Which model is better?\n- Sum of square errors much more common\n\n## Can we use a predictor to improve the model? {.smaller}\n\n::::{.columns}\n:::{.column}\n- $Y =$ `AvgSpeed`\n- $X =$ `Bike`\n:::\n\n:::{.column}\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_bar(~Bike, data = BikeCommute)\n```\n\n::: {.cell-output-display}\n![](01-welcome_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n:::\n::::\n## Model with a Binary Predictor\n\n- $Y = \\mu_i + \\epsilon$ where\n  +  $\\mu_1 =$ average speed for `Carbon` bikes, $Y\\sim N(\\mu_1, \\sigma_1)$\n  +  $\\mu_2 =$ average speed for `Steel` bikes, $Y\\sim N(\\mu_2, \\sigma_2)$\n- $$f(X) = \\left\\{\n\\begin{array}{l}\n\\mu_1, \\text{ if } X = \\text{Carbon}\\\\\n\\mu_2, \\text{ if } X = \\text{Steel}\\\\\n\\end{array}\n\\right.$$\n\n## Is this plausible?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_boxplot(AvgSpeed ~ Bike, data = BikeCommute) |> \n  gf_jitter(AvgSpeed ~ Bike, width = 0.05)\n```\n\n::: {.cell-output-display}\n![](01-welcome_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\n## Estimating the parameters {.smaller}\n\n::::{.columns}\n:::{.column}\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(AvgSpeed ~ Bike, data = BikeCommute) # Compute the mean of AvgSpeed for each level in Bike\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Carbon    Steel \n15.18731 15.03500 \n```\n\n\n:::\n\n```{.r .cell-code}\nsum(resid(lm(AvgSpeed ~ Bike, data = BikeCommute))^2) # Compute sum of squares\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28.50046\n```\n\n\n:::\n:::\n\n:::\n:::{.column}\n- $\\hat{\\mu_1} \\approx 12.19$\n- $\\hat{\\mu_2} \\approx 15.04$\n- New sum of squares is 28.5 which is less than 28.8 from our sample mean model\n- Is this model truly better?\n- How can we determine that?\n- Hint: it's the same as asking: \"Is there a difference between the means of the two groups?\"\n:::\n::::\n\n## Two-Sample T-Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(AvgSpeed~Bike, data = BikeCommute)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  AvgSpeed by Bike\nt = 0.76982, df = 47.649, p-value = 0.4452\nalternative hypothesis: true difference in means between group Carbon and group Steel is not equal to 0\n95 percent confidence interval:\n -0.2455673  0.5501827\nsample estimates:\nmean in group Carbon  mean in group Steel \n            15.18731             15.03500 \n```\n\n\n:::\n:::\n\n\n- What does p-value = 0.4452 mean?\n- Interpret the 95% confidence interval\n\n## Effect Size {.smaller}\n\n::::{.columns}\n:::{.column}\n- Is the difference (effect) large, relative to the variability in the population?\n- Many ways to quantify\n- This slide: Cohen's d\n  + 0.2~small\n  + 0.5~medium\n  + 1.0~large\n- Pooled standard deviation $$s_p = \\sqrt{\\frac{(n_1 - 1)s_1^2 + (n_2-1)s_2^2}{n_1+n_2-2}}$$\n- Effect Size $= \\frac{\\bar{y_1}-\\bar{y_2}}{s_p}$\n:::\n:::{.column}\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(effectsize)\ncohens_d(AvgSpeed~Bike, data = BikeCommute)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |        95% CI\n-------------------------\n0.21      | [-0.32, 0.74]\n\n- Estimated using pooled SD.\n```\n\n\n:::\n:::\n\n:::\n::::\n  \n\n\n<!-- ## Examples of regression in practice -->\n\n<!-- -   [New Yorkers Will Pay \\$56 A Month To Trim A Minute Off Their Commute](https://fivethirtyeight.com/features/new-yorkers-will-pay-56-a-month-to-trim-a-minute-off-their-commute/) -->\n\n<!-- -   [How FiveThirtyEight's 2020 Presidential Forecast Works --- And What's Different Because Of COVID-19](https://fivethirtyeight.com/features/how-fivethirtyeights-2020-presidential-forecast-works-and-whats-different-because-of-covid-19/) -->\n\n<!-- -   [Effect of Forensic Evidence on Criminal Justice Case Processing](https://onlinelibrary.wiley.com/doi/10.1111/1556-4029.12020) -->\n\n<!-- -   [Why it's so freaking hard to make a good COVID-19 model](https://fivethirtyeight.com/features/why-its-so-freaking-hard-to-make-a-good-covid-19-model/) (from March 2020) -->\n\n# STA 210\n\n## Course FAQ {.midi}\n\n**Q - What background is assumed for the course?**\n\nA - Introductory statistics or probability course at Duke\n\n. . .\n\n**Q - Will we be doing computing?**\n\nA - Yes. We will use the computing language R for analysis, Quarto for writing up results, and GitHub for version control and collaboration\n\n. . .\n\n**Q - Will we learn the mathematical theory of regression?**\n\nA - Yes and No. The course is primarily focused on application; however, we will discuss some of the mathematics of simple linear regression. There a 0.5-credit course [STA 211: Mathematics of Regression](https://stat.duke.edu/courses/mathematics-regression) to take simultaneously or after this course to dive into more of the mathematics.\n\n------------------------------------------------------------------------\n\n## Course learning objectives {.midi}\n\nBy the end of the semester, you will be able to...\n\n-   analyze real-world data to answer questions about multivariable relationships.\n\n-   use R to fit and evaluate linear and logistic regression models.\n\n-   assess whether a proposed model is appropriate and describe its limitations.\n\n-   use Quarto to write reproducible reports and GitHub for version control and collaboration.\n\n-   effectively communicate statistical results through writing and oral presentations.\n\n## Course topics {.midi}\n\n::: columns\n::: {.column width=\"50%\"}\n**Unit 1: Quantitative Response Variable**\n\n-   Simple Linear Regression\n\n-   Multiple Linear Regression\n\n<br>\n\n**Unit 2: Categorical Response Variable**\n\n-   Logistic Regression\n-   Multinomial logistic regression\n:::\n\n::: {.column width=\"50%\"}\n**Unit 3: Looking Ahead**\n\n-   Special topics\n\n-   Presenting statistical results\n:::\n:::\n\n# Course overview\n\n## Course toolkit {.midi}\n\n-   **Course website**: [sta210-fa23.netlify.app](https://sta210-fa23.netlify.app)\n    -   Central hub for the course!\n    -   **Tour of the website**\n-   **Sakai**: [sakai.duke.edu](https://sakai.duke.edu)\n    -   Gradebook\n    -   Announcements\n    -   Gradescope\n    -   Ed Discussion\n-   **GitHub:** [github.com/sta210-fa23](github.com/sta210-fa23)\n    -   Distribute assignments\n    -   Platform for version control and collaboration\n\n## Computing toolkit {.midi}\n\n::: columns\n::: {.column width=\"50%\"}\n::: {.fragment fragment-index=\"1\"}\n![](images/01/rstudio.png){fig-alt=\"RStudio logo\" fig-align=\"center\" width=\"5.61in\" height=\"1.6in\"}\n:::\n\n::: {.fragment fragment-index=\"2\"}\n-   All analyses using R, a statistical programming language\n\n-   Write reproducible reports in Quarto\n\n-   Access RStudio through [STA 210 Docker Containers](https://cmgr.oit.duke.edu/containers)\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: {.fragment fragment-index=\"1\"}\n![](images/01/github.png){fig-alt=\"GitHub logo\" fig-align=\"center\" width=\"5.61in\" height=\"1.6in\"}\n:::\n\n::: {.fragment fragment-index=\"3\"}\n-   Access assignments\n\n-   Facilitates version control and collaboration\n\n-   All work in [STA 210 course organization](https://github.com/sta210-fa23)\n:::\n:::\n:::\n\n# Activities + assessments\n\n## Prepare, Participate, Practice, Perform\n\n::: small\n::: incremental\n-   **Prepare:** Introduce new content and prepare for lectures by completing the readings (and sometimes watching the videos)\n\n-   **Participate:** Attend and actively participate in lectures and labs, office hours, team meetings\n\n-   **Practice:** Practice applying statistical concepts and computing with application exercises during lecture, graded for completion\n\n-   **Perform:** Put together what you've learned to analyze real-world data\n\n    -   Lab assignments (first individual, later team-based)\n\n    -   Homework assignments (individual)\n\n    -   Two exams\n\n    -   Final group project\n:::\n:::\n\n## Grading\n\n| Category              | Percentage |\n|-----------------------|------------|\n| Homework              | 35%        |\n| Final project         | 15%        |\n| Lab                   | 15%        |\n| Exam 01               | 15%        |\n| Exam 02               | 15%        |\n| Application Exercises | 2.5%       |\n| Teamwork              | 2.5%       |\n\nSee the [syllabus](https://sta210-fa23.netlify.app/syllabus.html) for details on how the final letter grade will be calculated.\n\n## Support\n\n-   Attend office hours to meet with a member of the teaching team\n    -   Prof. Tackett's office hours start Fri, Sep 1, 1 - 3pm\n    -   Full office hours schedule starts Tue, Sep 5\n-   Ask and answer questions on course discussion forum\n-   Use email for questions regarding personal matters and/or grades\n-   See the [Course Support](https://sta210-fa23.netlify.app/support.html) page for more details\n\n## Diversity & inclusion\n\n::: small\nIt is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength and benefit.\n\n-   If you have a name that differs from those that appear in your official Duke records, please let me know.\n\n-   Please let me know your preferred pronouns, if you are comfortable sharing.\n\n-   If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. If you prefer to speak with someone outside of the course, your advisers and deans are excellent resources.\n\n-   I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said or done in class (by anyone) that made you feel uncomfortable, please talk to me about it.\n:::\n\n## Accessibility\n\n-   The [Student Disability Access Office (SDAO)](https://access.duke.edu/students) is available to ensure that students are able to engage with their courses and related assignments.\n\n-   If you have documented accommodations from SDAO, please send the documentation as soon as possible.\n\n-   I am committed to making all course activities and materials accessible. If any course component is not accessible to you in any way, please don't hesitate to let me know.\n\n# Course policies\n\n## COVID-19 and other illness\n\n-   Please do not come to class if you have tested positive for COVID-19, have possible symptoms and have not yet been tested, or have other illness.\n\n-   Lecture recordings are available for excused absences. See [Lecture recording request](https://sta210-fa23.netlify.app/syllabus#lecture-recording-request) in the syllabus for more information and a link to the request form.\n\n-   Read and follow the university guidelines regarding COVID-19 at [coronavirus.duke.edu](https://coronavirus.duke.edu/).\n\n## Late work, waivers, and regrade requests\n\n-   We have policies! We will discuss them in detail when the first assignment is released.\n\n-   Read more about them in the [Course policies](https://sta210-fa23.netlify.app/syllabus.html#course-policies) section of the syllabus and refer back to them as needed\n\n-   If you have questions, email [sta210\\@duke.edu](mailto:%20sta210@duke.edu)\n\n## Academic integrity\n\n> To uphold the Duke Community Standard:\n>\n> -   I will not lie, cheat, or steal in my academic endeavors;\n>\n> -   I will conduct myself honorably in all my endeavors; and\n>\n> -   I will act if the Standard is compromised.\n\n\\\nBy participating in this course, you are agreeing that all your work and conduct will be in accordance with the Duke Community Standard.\n\n## Collaboration & sharing code\n\n-   We have policies! We will discuss them in detail when the first assignment is released.\n\n-   Read about them in the [Academic honesty](https://sta210-fa23.netlify.app/syllabus.html#academic-honesty) section of the syllabus and refer to them as needed\n\n## Use of artificial intelligence (AI) {.midi}\n\n-   You should treat AI tools, such as ChatGPT, the same as other online resources.\n-   There are two guiding principles that govern how you can use AI in this course:[^1]\n    -   \\(1\\) *Cognitive dimension:* Working with AI should not reduce your ability to think clearly. We will practice using AI to facilitate---rather than hinder---learning.\n    -   \\(2\\) *Ethical dimension***:** Students using AI should be transparent about their use and make sure it aligns with academic integrity.\n\n[^1]: These guiding principles are based on [*Course Policies related to ChatGPT and other AI Tools*](https://docs.google.com/document/d/1WpCeTyiWCPQ9MNCsFeKMDQLSTsg1oKfNIH6MzoSFXqQ/preview) developed by Joel Gladd, Ph.D.[↩︎](https://sta101-f23.github.io/course-syllabus.html#fnref1)\n\n## Use of artificial intelligence (AI) {.midi}\n\n✅ **AI tools for code:** You may make use of the technology for coding examples on assignments; if you do so, you must explicitly cite where you obtained the code.\n\n❌ **No AI tools for narrative:** Unless instructed otherwise, AI is [**not**]{.underline} permitted for writing narrative on assignments.\n\n::: callout-important\nIn general, you may use AI as a resource as you complete assignments but not to answer the exercises for you. You are ultimately responsible for the work you turn in; it should reflect your understanding of the course content.\n:::\n\n# Having a successful semester in STA 210\n\n## Five tips for success\n\n1.  Complete all the preparation work (readings and videos) before class.\n\n2.  Ask questions.\n\n3.  Do the homework and labs; get started on homework early when possible.\n\n4.  Don't procrastinate and don't let a week pass by with lingering questions.\n\n5.  Stay up-to-date on announcements on Ed Discussion and sent via email.\n\n# Questions?\n\nRaise your hand or post on Ed Discussion\n\n# Let's look at some data!\n\n## Application exercise\n\n::: appex\n📋 [AE 01 - Movie Budgets and Revenues](https://sta210-fa23.netlify.app/ae/ae-01-movies.html)\n:::\n\n# This week\n\n## For this week...\n\n-   Read the [syllabus](https://sta210-fa23.netlify.app/syllabus)\n\n-   See the [course schedule](https://sta210-fa23.netlify.app/schedule) for an overview of the semester\n\n-   Labs start this week!\n\n    -   Section 001: Labs on Tuesday\n\n    -   Section 002: Labs on Thursday\n\n-   This week's lab is focused on introductions and computing\n\n-   Wednesday's lecture: The Big Picture\n",
    "supporting": [
      "01-welcome_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}