project:
  type: website

website:
  page-navigation: true
  title: "MAT 212 - Fall 2024"
  description: "Homepage for MAT 212 - Multiple Regression Analysis at the College of Idaho, Fall 2024"
  site-url: https://mat212fa24.netlify.app/

  repo-url: https://github.com/EricFriedlander/MATH212FA24
  repo-actions: [edit, issue]
  
  page-footer:
    # background: "#412d5e"
    left: |
      &copy; Copyright 2024, Eric Friedlander
    right: |
      This site is built with [Quarto](https://quarto.org/)

  sidebar:
    # background: "#412d5e"
    logo: "images/logo.png"
    align: center
    tools: 
      # - icon: github
      #   href: https://github.com/sta210-fa23
      #   text: "GitHub organization"
      - icon: code-square
        href: https://rstudio.collegeofidaho.edu/
        text: "RStudio"
      - icon: person
        href: https://cofi.instructure.com/courses/15692
        text: "Canvas"
        # menu:
        #   - text: Canvas
        #     url: https://cofi.instructure.com/courses/15692
          # - text: Ed Discussion 
          #   url: https://edstem.org/us/courses/44523/discussion/
          # - text: Gradescope 
          #   url: https://www.gradescope.com/courses/584312
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - href: schedule.qmd
        text: Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: support.qmd
        text: Support
      - href: links.qmd
        text: Useful links
      - section: Computing
        contents: 
        - href: computing-access.qmd
          text: Access
        # - href: computing-troubleshooting.qmd
        #   text: Troubleshooting
        - href: computing-r-resources.qmd
          text: R resources
      - section: Project
        # contents:
        # - href: project-instructions.qmd
        #   text: Instructions
        # - href: project-tips.qmd
        #   text: Tips + resources
      # - href: stats-experience.qmd
      #   text: Statistics experience
      # - href: https://docs.google.com/spreadsheets/d/1dUD4SOpM79BL2kdvue9I2TP-ibcdxfpOIkHkMreYx64/edit?usp=sharing
      #   text: Lecture recordings

format:
  html:
    theme:
      - cosmo
      - theme.scss
    mainfont: "Open Sans"
    code-copy: true
    code-overflow: wrap
    toc: true

execute:
  freeze: auto

editor: source    
    



