---
title: "MAT 212: Multiple Regression Analysis"
subtitle: "Fall 2024 - Dr. Eric Friedlander"
navbar: false
---

# Overview

## Catalog Description
An introduction to statistical modeling and methods. Topics may include model construction and analysis using multiple linear regression, analysis of variance, and logistic regression. The course makes substantial use of statistical software. Students who have taken more than one calculus course should generally take MAT-212 rather than MAT-125.

## Eric's Addition
We will learn approaches for analyzing multivariate data sets, emphasizing analysis of variance, linear regression, and logistic regression. You will learn techniques for checking the appropriateness of proposed models, such as residual analyses and case influence diagnostics, and techniques for selecting models. Gain experience dealing with the challenges that arise in practice through assignments that utilize real-world data. This class emphasizes data analysis over mathematical theory.

# Class meetings

|             |                             |                     |
|-------------|-----------------------------|---------------------|
| **Lecture** | Mon/Wed/Fri 10:00 - 10:50am | BOON 132            |

## Instructor

Eric is an Assistant Professor in the Department of Mathematics and Physical Sciences at the College of Idaho. Blah

| Office hours         | Location      |
|----------------------|---------------|
| Insert   | Insert |
| *or by appointment.* |               |

<!-- ## Teaching assistants -->

<!-- ::: {.callout-tip appearance="simple" icon="false"} -->
<!-- [Clickhere](https://docs.google.com/spreadsheets/d/1bZMZsX0Z6-rMI_qguqZCPg3kaes7KTz5Cn7gtcm9nWk/edit?usp=sharing) for schedule of office hours. -->
<!-- ::: -->

<!-- | Name              | Role    |                             | -->
<!-- |-------------------|---------|-----------------------------| -->
<!-- | Sam Rosen         | Head TA | Lab 01: Tue 10:05 - 11:20am | -->
<!-- | Bethany Astor     | TA      | Lab 02: Tue 11:45am - 1pm   | -->
<!-- | Jon Campbell      | TA      |                             | -->
<!-- | Donald Cayton     | TA      | Lab 02: Tue 11:45am - 1pm   | -->
<!-- | Allison Li        | TA      |                             | -->
<!-- | Mitchelle Mojekwu | TA      | Lab 04: Thu 11:45am - 1pm   | -->
<!-- | Ben Thorpe        | TA      |                             | -->
<!-- | Linxuan Wang      | TA      | Lab 03: Thu 10:05 - 11:20am | -->
<!-- | Xiaojun Zheng     | TA      | Lab 04: Thu 11:45am - 1pm   | -->
