---
title: "Course support"
---

We expect everyone will have questions at some point in the semester, so we want to make sure you can identify when that is and feel comfortable seeking help.

## Lectures

If you have a question during lecture, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.

## Office hours

I am here to help you be successful in the course. You are encouraged to attend office hours during the times posted on the home page to ask questions about the course content and assignments. A lot of questions are most effectively answered in-person, so office hours are a valuable resource. I encourage you to take advantage of them!

Make a pledge to stop by office hours at least once during the first three weeks of class. If you truly have no questions to ask, just stop by and say hi and introduce yourself.

## Canvas Discussion Forum

Outside of class and office hours, any general questions about course content or assignments should be posted on the [Canvas Discussion Forum](https://cofi.instructure.com/courses/15692/discussion_topics/64872). There is a chance another student has already asked a similar question, so please check the other posts on Ed Discussion before adding a new question. If you know the answer to a question that is posted, I encourage you to respond!

## Email

If you have questions about personal matters that are not appropriate for the class discussion forum (e.g. illness, accommodations, etc.), you may email Professor Fridlander at <efriedlander@collegeofidaho.edu>. **If you email me, please include "MAT 212" in the subject line.** Barring extenuating circumstances, I will respond to MAT 212 emails within 48 hours Monday - Friday. Response time may be slower for emails sent Friday evening - Sunday.
