---
title: Syllabus
format: 
  html: default
  pdf: default
---

## Course info

### Class meetings

|             |                           |                     |
|-------------|---------------------------|---------------------|
| **Lecture** | Mon, Wed, Fri 10:00 - 10:50am | Boone 132       |
| **Office Hours** | Monday | 2:30-3:30pm | Boone 12B     |
| **Office Hours** | Tuesday | 9:45-10:45am | Boone 126B       |
| **Office Hours** | Wednesday | 1:30-2:30pm| Boone 126B       |
| **Office Hours** | Thursday | 1-2pm | Boone 126B       |
| **Final Presentation** | Wednesday, December 11th | 8:30-11am | TBD |

Office hours are also available by appointment, just email me!


### Instructor & Office Hours

**Instructor**: Professor Eric Friedlander
**Office**: Boone 126B
**Email**: <efriedlander@collegeofidaho.edu>

## Course Learning Objectives

By the end of the semester, you will be able to...
-   analyze real-world data to answer questions about multivariable relationships.
-   use R to fit and evaluate linear and logistic regression models.
-   assess whether a proposed model is appropriate and describe its limitations.
-   use Quarto to write reproducible reports and GitHub for version control and collaboration.
-   effectively communicate statistical results through writing and oral presentations.

## Course community

### College of Idaho Honor Code

> The College of Idaho maintains that academic honesty and integrity are essential values in the educational process. Operating under an Honor Code philosophy, the College expects conduct rooted in honesty, integrity, and understanding, allowing members of a diverse student body to live together and interact and learn from one another in ways that protect both personal freedom and community standards. Violations of academic honesty are addressed primarily by the instructor and may be referred to the [Student Judicial Board](https://collegeofidaho.smartcatalogiq.com/en/current/Undergraduate-Catalog/Policies-and-Procedures/Academic-Misconduct).

By participating in this course, you are agreeing that all your work and conduct will be in accordance with the College of Idaho Honor Code.

### Disability Accommodation Statement

The College of Idaho seeks to provide an educational environment that is accessible to the needs of students with disabilities. The College provides reasonable services to enrolled students who have a documented permanent or temporary physical, psychological, learning, intellectual, or sensory disability that qualifies the student for accommodations under the Americans with Disabilities Act or section 504 of the Rehabilitation Act of 1973. If you have, or think you may have, a disability that impacts your performance as a student in this class, you are encouraged to arrange support services and/or accommodations through the Department of Accessibility and Learning Excellence located in McCain 201B and available via email at <accessibility@collegeofidaho.edu>. Reasonable academic accommodations may be provided to students who submit appropriate and current documentation of their disability. Accommodations can be arranged only through this process and are not retroactively applied. More information can be found on the DALE webpage (<https://www.collegeofidaho.edu/accessibility>).


### Communication

All lecture notes, assignment instructions, an up-to-date schedule, and other course materials may be found on the course website, [mat212fa24.netlify.app](https://mat212fa24.netlify.app).

Periodic announcements will be sent via email and will also be available through Canvas and grades will be stored in the Canvas gradebook. Please check your email regularly to ensure you have the latest announcements for the course.

### In class agreements

If we discuss/agree to something in class or office hours which requires action from me (e.g. “you may turn in your homework late due to a sporting event”), you MUST send me a follow-up message. If you don’t, I will almost certainly forget, and our agreement will be considered null and void.

### Getting help in the course

-   If you have a question during lecture or lab, feel free to ask it! There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.
-   I am here to help you be successful in the course. You are encouraged to attend *office hours*[^1] to ask questions about the course content and assignments. Many questions are most effectively answered as you discuss them with others, so office hours are a valuable resource. You are encouraged to use them!
-   Outside of class and office hours, any general questions about course content or assignments should be posted on the class discussion forum on [Canvas](https://cofi.instructure.com/courses/15692/discussion_topics/64872). There is a chance another student has already asked a similar question, so please check the other posts in Canvas before adding a new question. If you know the answer to a question posted in the discussion forum, you are encouraged to respond!

[^1]: Office hours are times the teaching team set aside each week to meet with students. [Click here](https://learningcenter.unc.edu/tips-and-tools/using-office-hours-effectively/) to learn more about how to effectively use office hours.

### Email

If you have questions about assignment extensions or accommodations, please email <efriedlander@collegeofidaho.edu>. Please see [Late work policy] for more information. **If you email me, please include "MAT 212" in the subject line.** Barring extenuating circumstances, I will respond to MAT 212 emails within 48 hours Monday - Friday. Response time may be slower for emails sent Friday evening - Sunday.

Check out the [Support](support.qmd) page for more resources.

## Textbook

The official textbook for this course is:

-   Stat2: Modeling with Regression and ANOVA, 2nd ed. by Cannon et al.

In addition, readings may be assigned from the following texts (all freely available online).

-   [R for Data Science](https://r4ds.had.co.nz/) by Garret Grolemund and Hadley Wickham

-   [Introduction to Modern Statistics](https://openintro-ims.netlify.app/) by Mine Çetinkaya-Rundel and Johanna Hardin

-   [Tidy modeling with R](https://www.tmwr.org/) by Max Kuhn and Julia Silge

-   [Beyond Multiple Linear Regression](https://bookdown.org/roback/bookdown-BeyondMLR/) by Paul Roback and Julie Legler

## Lectures

Lectures are designed to be interactive, so you gain experience applying new concepts and learning from each other. My role as instructor is to introduce you to new methods, tools, and techniques, but it is up to you to take them and make use of them. A lot of what you do in this course will involve writing code, and coding is a skill that is best learned by doing. Therefore, as much as possible, you will be working on a variety of tasks and activities throughout each lecture and lab. You are expected to prepare for class by completing assigned readings, attend all lecture sessions, and meaningfully contribute to in-class exercises and discussion. Additionally, some lectures will feature application exercises that will be graded based on completing what we do in class.

You are expected to bring a laptop, tablet, or Chromebook to each class so that you can participate in the in-class exercises. Please make sure your device is fully charged before you come to class, as the number of outlets in the classroom may not be sufficient to accommodate everyone.

## Activities & Assessment

You will be assessed based on five components: application exercises, homework, exams, project, and oral R quiz

### Application Exercises

Parts of some lectures will be dedicated to working on Application Exercises (AEs). These exercises which give you an opportunity to practice applying the statistical concepts and code introduced in the prepare assignment. These AEs are due within three days of the corresponding lecture period. Specifically, AEs from Monday lectures are due Thursday by 11:59p MT, AEs from Wednesday lectures are due Saturday by 11:59p MT, and AEs from Friday lectures are due Monday at 12:59p MT.

Because these AEs are for practice, they will be graded based on making a good-faith effort in attempting all questions covered in class. You are welcome to, but not required, to work on AEs beyond lecture. Successful on-time effort on at least 80% of AEs will result in full credit for AEs in the final course grade. Because AEs are intended for in-class activities, there are no extensions given on AEs.

### Homework

In homework, you will apply what you've learned during lecture to complete data analysis tasks. You may discuss homework assignments with other students; however, homework should be completed and submitted individually. Similar to lab assignments, homework must be typed up using Quarto and submitted as a .Qmd file in Canvas.

### Exams

There will be two exams in this course. Each exam will include a closed-notes in-class component and may contain an open-note take-home component. Through these exams you have the opportunity to demonstrate what you've learned in the course thus far. The exams will focus on both conceptual understanding of the content and application through analysis and computational tasks. The content of the exam will be related to the content in reading assignments, lectures, application exercises, and homework assignments. More detail about the exams will be given during the semester.

### Project

The purpose of the [final project](/project/) is to apply what you've learned throughout the semester to analyze an interesting data-driven research question. The project will be completed with your in pairs, and each team will present their work through a written report and poster presentation taking place during the final exam period. More information about the project will be provided during the semester.

### Oral R Quiz

-	The purpose of this Quiz is to test your knowledge of the basic R functions we use regularly, R syntax, and your R "workflow". Do you know the basic functions? If you run into a (common) error, can you debug it yourself? Can you interpret the R Help menu? Do you understand common terminology (e.g. "argument", "function", "output")?
-	Each student will take sign up for a 20-minute time slot to take the Quiz via Teams.  Slots will open in early September and close on November 15th.
-	The R Quiz will be graded: “Proficient” (5 points), “In Progress” (3 points), or “Unsatisfactory” (0 points)
-	Each student who earns “In Progress” or below is allowed one retake before November 15th, but this retake must be at least one week after their first attempt.
-	The specific questions asked during the Oral R Quiz will be different for every student and for every attempt, although similar in style and difficulty.


## Grading

The final course grade will be calculated as follows:

<center>

| Category              | Percentage |
|-----------------------|------------|
| Homework              | 25%        |
| Final project         | 30%        |
| Exam 01               | 15%        |
| Exam 02               | 20%        |
| Application Exercises | 5%         |
| Oral R Quiz           | 5%         |

</center>

<br>

The final letter grade will be determined based on the following thresholds:

<center>

| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |

</center>

## Five tips for success

Your success on this course depends very much on you and the effort you put into it. The course has been organized so that the burden of learning is on you. I will help you by providing you with materials and answering questions and setting a pace, but for this to work you must do the following:

1.  Complete all the preparation work before class.

2.  Ask questions. As often as you can. In class, out of class. Ask me, ask your friends, ask the person sitting next to you. This will help you more than anything else. If you get a question wrong on an assessment, ask why. If you're not sure about the homework, ask. If you hear something on the news that sounds related to what we discussed, ask. If the reading is confusing, ask.

3.  Do the readings.

4.  Do the homework. The earlier you start, the better. It's not enough to just mechanically plow through the exercises. You should ask yourself how these exercises relate to earlier material, and imagine how they might be changed (to make questions for an exam, for example.)

5.  Don't procrastinate. The content builds upon what was taught in previous weeks, so if something is confusing to you in Week 2, Week 3 will become more confusing, Week 4 even worse, etc. Don't let the week end with unanswered questions. But if you find yourself falling behind and not knowing where to begin asking, come to office hours and I can help you identify a good (re)starting point.

## Course policies

### Academic honesty

**TL;DR: Don't cheat!**

-   The homework assignments must be completed individually but you are welcome to discuss the assignment with classmates (e.g., discuss what's the best way for approaching a problem, what functions are useful for accomplishing a particular task, etc.). However you may not directly share (i.e. via copy/paste or copying) answers to homework questions (including and especially any code) with anyone other than myself.

-   You may not discuss or otherwise work with others on the exams. Unauthorized collaboration or using unauthorized materials will be considered a violation for all students involved. More details will be given closer to the exam date.

-   For the projects, collaboration within teams is not only allowed, but expected. Communication between teams at a high level is also allowed however you may not share code or components of the project across teams.

-   **Reusing code**: Unless explicitly stated otherwise, you may make use of online resources (e.g. StackOverflow) for coding examples on assignments. If you directly use code from an outside source (or use it as inspiration), you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.

-   **Use of artificial intelligence (AI)**: You should treat AI tools, such as ChatGPT, the same as other online resources. There are two guiding principles that govern how you can use AI in this course:[^2] (1) *Cognitive dimension:* Working with AI should not reduce your ability to think clearly. We will practice using AI to facilitate---rather than hinder---learning. (2) *Ethical dimension***:** Students using AI should be transparent about their use and make sure it aligns with academic integrity.

    -   **AI tools for code:** You may make use of the technology for coding examples on assignments; if you do so, you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism. You may use [these guidelines](https://guides.lib.monash.edu/c.php?g=219786&p=6972087) for citing AI-generated content.

    -   **No AI tools for narrative:** Unless instructed otherwise, AI is [**not**]{.underline} permitted for writing narrative on assignments. In general, you may use AI as a resource as you complete assignments but not to answer the exercises for you. You are ultimately responsible for the work you turn in; it should reflect your understanding of the course content.

[^2]: These guiding principles are based on [*Course Policies related to ChatGPT and other AI Tools*](https://docs.google.com/document/d/1WpCeTyiWCPQ9MNCsFeKMDQLSTsg1oKfNIH6MzoSFXqQ/preview) developed by Joel Gladd, Ph.D.[↩︎](https://sta101-f23.github.io/course-syllabus.html#fnref1)

If you are unsure if the use of a particular resource complies with the academic honesty policy, please ask.

Regardless of course delivery format, it is the responsibility of all students to understand and follow all College of Idaho policies, including academic integrity (e.g., completing one's own work, following proper citation of sources, adhering to guidance around group work projects, and more). Ignoring these requirements is a violation of the Honor Code.

### Late work policy

The due dates for assignments are there to help you keep up with the course material and to ensure the teaching team can provide feedback within a timely manner. I understand that things come up periodically that could make it difficult to submit an assignment by the deadline.

-   **Late Homework:** There will be a 5% deduction for each 24-hour period the assignment is late for the first two days. After 2 days, students will receive a 30% reduction. No homework will be accepted after it is returned to the class

-   **Late Application Exercises:** AEs are due three days after the class they are assigned. No late work is accepted for application exercises, since these are designed as in-class activities to help you prepare for homework. 

-   **School-Sponsored Events/Illness:** If an application exercise, exam, or final project must be missed due to a school-sponsored event, you must let me know at least a week ahead of time so that we can schedule a time for you to make up the work before you leave. If you must miss a exam of the final project due to illness, you must let me know before class that day so that we can schedule a time for you to take a make-up quiz or exam. Failure to adhere to this policy will result in a 35% penalty the corresponding assignment.  

### Regrade Requests

Regrade requests must be submitted via email within a week of when an assignment is returned. Regrade requests will be considered if there was an error in the grade calculation or if you feel a correct answer was mistakenly marked as incorrect. Requests to dispute the number of points deducted for an incorrect response will not be considered. Note that by submitting a regrade request, the entire question will be graded which could potentially result in losing points.

*No grades will be changed after the final project presentations.*

## Important dates

-   **Aug 21:** Classes begin
-   **Sep 4:** Last day to drop
-   **Oct 14 - 18**: Fall break
-   **Nov 18**: Last day to withdraw with W
-   **Nov 28 - 29:** Thanksgiving recess
-   **Dec 6**: Classes end
-   **Dec 11**: Final presentation

