---
title: "Exam 02 review"
author: "Prof. Eric Friedlander"
date: "2024-11-25"
date-format: "MMM DD, YYYY"
footer: "[🔗 MAT 212 - Fall 2024 -  Schedule](https://mat212fa24.netlify.app/schedule)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: false
    incremental: false 
    chalkboard: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
  cache: false
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

## Announcements {.small}

-   Due dates
    -   Project paper due Friday, December 6th at 11:59PM
    -   Poster due Monday, December 9th at 9AM
        -   Make sure to submit to printer
    -   [Poster Presentations](https://mat212fa24.netlify.app/project-instructions.html#poster-presentation) Wednesday December 8:30-11AM
        -   I will bring treats and coffee
        -   Make sure you are able to discuss your poster
-   Please fill out course evaluations
-   Last week of class
    -   Finish final lecture and then work on Projects

## Exam 02 {.midi}

-   20% of final course grade

## Content: Weeks 10 - 14 {.midi}

-   Fitting, interpreting, comparing, and evaluating multiple linear regression models

-   Inference for multiple linear regression

-   Conditions for multiple linear regression including multicollinearity

-   Probabilities, odds, and odds ratios

-   Fitting, interpreting, and comparing logistic regression models

## Practice

::: appex
📋 [Exam 2 Review](../ae/exam-02-review.html)
:::

