{
  "hash": "7e16d2d545fa4af61ee3cb307d28f590",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple Logistic Regression\"\nauthor: \"Prof. Eric Friedlander\"\ndate: \"2024-11-22\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 MAT 212 - Fall 2024 -  Schedule](https://mat212fa24.netlify.app/schedule)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  cache: false\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n\n## Do now\n\nGet back in your groups from Wednesday and finish AE-23.\n\n## Announcements\n\n-   [Peer Review due Monday, November 25th](https://mat212fa24.netlify.app/project-instructions#peer-review)\n\n-   HW 10 due Monday, November 25th\n    \n-   Midterm 2 Wednesday, November 27th (day before break)\n\n::: appex\n📋 [AE 24 - Logistic Regression: Selection and Comparison](https://mat212fa24.netlify.app/ae/ae-24-compare-logistic)\n\n- Open up AE 24.\n:::\n\n## Topics\n\n-   Investigating interaction terms in logistic regression models\n\n-   Comparing logistic regression models\n\n-   Choosing logistic regression models\n\n-   Transformations in logistic regression\n\n## Computational setup\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(openintro)\nlibrary(knitr)\nlibrary(kableExtra)  # for table embellishments\nlibrary(Stat2Data)   # for empirical logit\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_bw(base_size = 20))\n```\n:::\n\n\n# Data\n\n## Risk of coronary heart disease {.midi}\n\nThis data set is from an ongoing cardiovascular study on residents of the town of Framingham, Massachusetts. We want to examine the relationship between various health characteristics and the risk of having heart disease.\n\n-   `TenYearCHD`:\n\n    -   1: Developed heart disease in next 10 years\n    -   0: Did not develop heart disease in next 10 years\n\n-   `age`: Age at exam time (in years)\n\n-   `education`: 1 = Some High School, 2 = High School or GED, 3 = Some College or Vocational School, 4 = College\n\n## Data prep\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease <- read_csv(\"data/framingham.csv\") |>\n  select(TenYearCHD, age, education, male, diaBP) |>\n  drop_na() |> \n  mutate(education = as.factor(education),\n         male = as.factor(male))\n         \n\nheart_disease |> head() |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| TenYearCHD| age|education |male | diaBP|\n|----------:|---:|:---------|:----|-----:|\n|          0|  39|4         |1    |    70|\n|          0|  46|2         |0    |    81|\n|          0|  48|1         |1    |    80|\n|          1|  61|3         |0    |    95|\n|          0|  46|3         |0    |    84|\n|          0|  43|2         |0    |   110|\n\n\n:::\n:::\n\n# Interaction Terms\n\n## Interactions\n\n**Intuitively:** There is an interaction between two variables when the influence of one variables on the log-odds depends on what the value of the other variable is.\n\n. . .\n\nComplete Exercise 1. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncountdown::countdown(minutes = 1, seconds=30)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"countdown\" id=\"timer_417921ce\" data-update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">01</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">30</span></code>\n</div>\n```\n\n:::\n:::\n\n## Recall: Empirical Logit Plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemplogitplot1(TenYearCHD ~ age, data = heart_disease,\n              ngroups = 10)\n```\n\n::: {.cell-output-display}\n![](31-logistic-comparison_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n:::{.question}\nHow do we interpret this?\n:::\n\n\n## Visualizing Interactions (Quant vs. Cat)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemplogitplot2(TenYearCHD ~ age + male, data = heart_disease,\n              ngroups = 10)\n```\n\n::: {.cell-output-display}\n![](31-logistic-comparison_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n. . .\n\nComplete Exercise 2.\n\n## Visualizing Interactions (Quant vs. Cat)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemplogitplot2(TenYearCHD ~ age + education, data = heart_disease,\n              ngroups = 10)\n```\n\n::: {.cell-output-display}\n![](31-logistic-comparison_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n:::{.question}\nBased on this plot, do you think there is an interaction between age and education?\n:::\n\n## Models with Interaction \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nage_male_interaction_model <- glm(TenYearCHD ~ age + male + age*male, \n                  data = heart_disease, family = \"binomial\")\n\nage_male_interaction_model |> tidy() |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -6.358|     0.428|   -14.865|   0.000|\n|age         |    0.085|     0.008|    10.883|   0.000|\n|male1       |    1.308|     0.583|     2.245|   0.025|\n|age:male1   |   -0.014|     0.011|    -1.342|   0.180|\n\n\n:::\n:::\n\n\n## Models with Interaction\n\nTwo model's in one!\n\n-   Non-male's: $$\\log\\left(\\frac{\\hat{p}}{1-\\hat{p}}\\right) = -6.358 +0.085\\times\\text{age}$$\n-   Male's: \n$$\n\\begin{aligned} \\log\\left(\\frac{\\hat{p}}{1-\\hat{p}}\\right) &= (-6.358+1.308) +(0.085-0.015)\\times\\text{age}\\\\\n&=  -5.05 +0.070\\times\\text{age}\n\\end{aligned}\n$$\n\n. . .\n\nComplete Exercises 3 and 4.\n\n\n# Model selection\n\n## AIC or BIC for model selection\n\n$$\n\\begin{align}\n&AIC = - 2 * \\log L - {\\color{purple}n\\log(n)}+ 2(p +1)\\\\[5pt]\n&BIC =- 2 * \\log L - {\\color{purple}n\\log(n)} + \\log(n)\\times(p+1)\n\\end{align}\n$$\n\n## AIC from the `glance()` function\n\nLet's look at the AIC for model we fit earlier\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglance(age_male_interaction_model)$AIC\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3277.159\n```\n\n\n:::\n:::\n\n\n. . .\n\n**Calculating AIC**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n- 2 * glance(age_male_interaction_model)$logLik + 2 * (3+1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3277.159\n```\n\n\n:::\n:::\n\n\n## Comparing the models using AIC\n\nLet's compare a few models:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#|code-line-numbers: |6\nage_model <- glm(TenYearCHD ~ age, data = heart_disease, family = \"binomial\")\nage_male_model <- glm(TenYearCHD ~ age+male, data = heart_disease, family = \"binomial\") \nage_education_model <-  glm(TenYearCHD ~ age+education, data = heart_disease, family = \"binomial\")\nage_male_education_model <-  glm(TenYearCHD ~ age+ male + education, data = heart_disease, family = \"binomial\")\nage_education_interaction_model <-  glm(TenYearCHD ~ age + education + age* education, data = heart_disease, family = \"binomial\")\nall_interaction_model <-  glm(TenYearCHD ~ (age + education + male)^2, data = heart_disease, family = \"binomial\")\n```\n:::\n\n\n## Comparing the models using AIC\n\nLet's compare a few models:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naics <- c(glance(age_model)$AIC,\nglance(age_male_model)$AIC,\nglance(age_male_interaction_model)$AIC,\nglance(age_education_model)$AIC,\nglance(age_male_education_model)$AIC,\nglance(age_education_interaction_model)$AIC,\nglance(all_interaction_model)$AIC)\n\naics\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3310.680 3276.964 3277.159 3310.135 3279.342 3314.815 3285.196\n```\n\n\n:::\n:::\n\n<br>\n\n::: question\nBased on AIC, which model would you choose? Raise you hand if your AIC is better.\n:::\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwhich.min(aics)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n\n\n## Comparing the models using BIC\n\nLet's compare the models using BIC\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbics <- c(glance(age_model)$AIC,\nglance(age_male_model)$AIC,\nglance(age_male_interaction_model)$AIC,\nglance(age_education_model)$AIC,\nglance(age_male_education_model)$AIC,\nglance(age_education_interaction_model)$AIC,\nglance(all_interaction_model)$AIC)\n\naics\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3310.680 3276.964 3277.159 3310.135 3279.342 3314.815 3285.196\n```\n\n\n:::\n:::\n\n\n<br>\n\n::: question\nBased on BIC, which model would you choose? Raise your hand if your BIC is better.\n\n:::\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwhich.min(bics)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n## Choosing a Logistic Regression Model\n\n-   Forward/Backward/Stepwise selection all work in the same way\n-   Can you string together a sequence of Likelihood Ratio Tests (but only a few)\n\n# Transformations\n\n## Power Family of Transformation\n\n-   Many departures from linearity can be solved with power transformations (e.g. $X^{power}$)\n\n    +   For technical reasons, $power = 0$ corresponds to $\\log$\n    \n-   Look at empirical log-odds plot\n\n-   Concave down pattern $\\Rightarrow$ transform down (i.e. $power < 1$)\n\n    +   $\\log$ is typically a good first choice\n\n-   Concave up pattern $\\Rightarrow$ transform up (i.e. $power > 1$)\n\n\n## Empirical Log-Odds Plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemplogitplot1(TenYearCHD ~ diaBP, data = heart_disease, ngroups = 4)\n```\n\n::: {.cell-output-display}\n![](31-logistic-comparison_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Empirical Log-Odds Plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemplogitplot1(TenYearCHD ~ diaBP, data = heart_disease, ngroups = 4)\n```\n\n::: {.cell-output-display}\n![](31-logistic-comparison_files/figure-revealjs/unnamed-chunk-17-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n:::{.question}\nConcave up or down?\n:::\n\n## Empirical Log-Odds Plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease <- heart_disease |> mutate(diaBP_transformed = diaBP^2)\nemplogitplot1(TenYearCHD ~ diaBP_transformed, data = heart_disease, ngroups = 4)\n```\n\n::: {.cell-output-display}\n![](31-logistic-comparison_files/figure-revealjs/unnamed-chunk-18-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Empirical Log-Odds Plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease <- heart_disease |> mutate(diaBP_transformed = diaBP^10)\nemplogitplot1(TenYearCHD ~ diaBP_transformed, data = heart_disease, ngroups = 4)\n```\n\n::: {.cell-output-display}\n![](31-logistic-comparison_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Empirical Log-Odds Plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease <- heart_disease |> mutate(diaBP_transformed = diaBP^6)\nemplogitplot1(TenYearCHD ~ diaBP_transformed, data = heart_disease, ngroups = 4)\n```\n\n::: {.cell-output-display}\n![](31-logistic-comparison_files/figure-revealjs/unnamed-chunk-20-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n\n\n## Recap\n\n-   Interaction terms in logistic regression models\n\n    +   For quantitative-categorical, creates nested models\n\n-   Comparing logistic regression models\n\n    +   AIC/BIC\n\n-   Choosing logistic regression models\n\n    +   Same selection techniques as linear regression\n\n-   Transformations in logistic regression\n\n    +   Can only transform $X$\n  \n    +   Concave [up/down] $\\Rightarrow$ power-transform [up/down]\n\n",
    "supporting": [
      "31-logistic-comparison_files\\figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/countdown-0.4.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/countdown-0.4.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}