{
  "hash": "03f21d12bc306dcd142cecf0e69bd2eb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple linear regression (MLR)\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"2023-09-27\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 210 - Fall 2023 -  Schedule](https://sta210-fa23.netlify.app/schedule)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n## Announcements {.midi}\n\n-   HW 02 due Mon, Oct 2 at 11:59pm.\n-   All lecture recordings available until Wed, Oct 4 at 9am.\n    -   [Click here](https://docs.google.com/spreadsheets/d/1dUD4SOpM79BL2kdvue9I2TP-ibcdxfpOIkHkMreYx64/edit?usp=sharing) for link to videos. You can also find the link in the navigation bar of the course website.\n-   Lab groups start this week. You will get your assigned group when you go to lab.\n-   Submit questions about SLR by Thu, Sep 28. These questions will be used to make the Exam Review. [Click here](https://sta210-fa23.netlify.app/slides/08-slr-model-eval#/questions-about-slr) for more info.\n-   Exam 01: Wed, Oct 4 (in-class + take-home)\n-   Exam 01 review: Mon, Oct 2\n\n## Computational setup\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(openintro)\nlibrary(patchwork)\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(colorblindr)\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_minimal(base_size = 16))\n```\n:::\n\n\n\n# Considering multiple variables\n\n## Data: Peer-to-peer lender\n\nToday's data is a sample of 50 loans made through a peer-to-peer lending club. The data is in the `loan50` data frame in the **openintro** R package.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 50 × 4\n   annual_income debt_to_income verified_income interest_rate\n           <dbl>          <dbl> <fct>                   <dbl>\n 1         59000         0.558  Not Verified            10.9 \n 2         60000         1.31   Not Verified             9.92\n 3         75000         1.06   Verified                26.3 \n 4         75000         0.574  Not Verified             9.92\n 5        254000         0.238  Not Verified             9.43\n 6         67000         1.08   Source Verified          9.92\n 7         28800         0.0997 Source Verified         17.1 \n 8         80000         0.351  Not Verified             6.08\n 9         34000         0.698  Not Verified             7.97\n10         80000         0.167  Source Verified         12.6 \n# ℹ 40 more rows\n```\n\n\n:::\n:::\n\n\n\n## Variables\n\n**Predictors**:\n\n::: nonincremental\n-   `annual_income`: Annual income\n-   `debt_to_income`: Debt-to-income ratio, i.e. the percentage of a borrower's total debt divided by their total income\n-   `verified_income`: Whether borrower's income source and amount have been verified (`Not Verified`, `Source Verified`, `Verified`)\n:::\n\n**Outcome**: `interest_rate`: Interest rate for the loan\n\n## Outcome: `interest_rate`\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09-mlr-old_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|  min| median|  max|   iqr|\n|----:|------:|----:|-----:|\n| 5.31|   9.93| 26.3| 5.755|\n\n\n:::\n:::\n\n\n\n## Predictors {.small}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09-mlr-old_files/figure-html/unnamed-chunk-4-1.png){width=100%}\n:::\n:::\n\n\n\n## Data manipulation 1: Rescale income\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan50 <- loan50 |>\n  mutate(annual_income_th = annual_income / 1000)\n\nggplot(loan50, aes(x = annual_income_th)) +\n  geom_histogram(binwidth = 20) +\n  labs(title = \"Annual income (in $1000s)\", \n       x = \"\")\n```\n\n::: {.cell-output-display}\n![](09-mlr-old_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n## Outcome vs. predictors {.small}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09-mlr-old_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n## Single vs. multiple predictors\n\nSo far we've used a *single predictor variable* to understand variation in a quantitative response variable\n\n. . .\n\nNow we want to use *multiple predictor variables* to understand variation in a quantitative response variable\n\n# Multiple linear regression\n\n## Multiple linear regression (MLR) {.smaller}\n\nBased on the analysis goals, we will use a **multiple linear regression** model of the following form\n\n$$\n\\begin{aligned}\\hat{\\text{interest_rate}} ~ = \n\\hat{\\beta}_0 & + \\hat{\\beta}_1 \\text{debt_to_income} \\\\ & + \\hat{\\beta}_2 \\text{verified_income} \\\\ &+ \\hat{\\beta}_3 \\text{annual_income_th}\n\\end{aligned}\n$$\n\nSimilar to simple linear regression, this model assumes that at each combination of the predictor variables, the values `interest_rate` follow a Normal distribution.\n\n## Multiple linear regression\n\n**Recall:** The simple linear regression model assumes\n\n$$\nY|X\\sim N(\\beta_0 + \\beta_1 X, \\sigma_{\\epsilon}^2)\n$$\n\n. . .\n\n**Similarly:** The multiple linear regression model assumes\n\n$$\nY|X_1, X_2, \\ldots, X_p \\sim N(\\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\dots + \\beta_p X_p, \\sigma_{\\epsilon}^2)\n$$\n\n## Multiple linear regression\n\nAt any combination of the predictors, the mean value of the response $Y$, is\n\n$$\n\\mu_{Y|X_1, \\ldots, X_p} = \\beta_0 + \\beta_1 X_{1} + \\beta_2 X_2 + \\dots + \\beta_p X_p\n$$\n\n. . .\n\nUsing multiple linear regression, we can estimate the mean response for any combination of predictors\n\n$$\n\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 X_{1} + \\hat{\\beta}_2 X_2 + \\dots + \\hat{\\beta}_p X_{p}\n$$\n\n## Model fit {.smaller}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                           | estimate| std.error| statistic| p.value|\n|:------------------------------|--------:|---------:|---------:|-------:|\n|(Intercept)                    |   10.726|     1.507|     7.116|   0.000|\n|debt_to_income                 |    0.671|     0.676|     0.993|   0.326|\n|verified_incomeSource Verified |    2.211|     1.399|     1.581|   0.121|\n|verified_incomeVerified        |    6.880|     1.801|     3.820|   0.000|\n|annual_income_th               |   -0.021|     0.011|    -1.804|   0.078|\n\n\n:::\n:::\n\n\n\n## Model equation\n\n$$\n\\begin{align}\\hat{\\text{interest_rate}} =  10.726 &+0.671 \\times \\text{debt_to_income}\\\\\n&+ 2.211 \\times \\text{source_verified}\\\\  \n&+ 6.880 \\times \\text{verified}\\\\\n& -0.021 \\times \\text{annual_income_th}\n\\end{align}\n$$\n\n::: callout-note\nWe will talk about why there are two terms in the model for `verified_income` shortly!\n:::\n\n## Interpreting $\\hat{\\beta}_j$\n\n-   The estimated coefficient $\\hat{\\beta}_j$ is the expected change in the mean of $y$ when $x_j$ increases by one unit, <i>holding the values of all other predictor variables constant</i>.\n\n. . .\n\n-   **Example:** The estimated coefficient for `debt_to_income` is 0.671. This means for each point in an borrower's debt to income ratio, the interest rate on the loan is expected to be greater by 0.671%, holding annual income and income verification constant.\n\n## Prediction\n\n::: question\nWhat is the predicted interest rate for an borrower with an debt-to-income ratio of 0.558, whose income is not verified, and who has an annual income of \\$59,000?\n:::\n\n<br>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n10.726 + 0.671 * 0.558 + 2.211 * 0 + 6.880 * 0 - 0.021 * 59\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.861418\n```\n\n\n:::\n:::\n\n\n\n. . .\n\nThe predicted interest rate for an borrower with with an debt-to-income ratio of 0.558, whose income is not verified, and who has an annual income of \\$59,000 is 9.86%.\n\n## Prediction, revisited {.midi}\n\nJust like with simple linear regression, we can use the `predict()` function in R to calculate the appropriate intervals for our predicted values:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_borrower <- tibble(\n  debt_to_income  = 0.558, \n  verified_income = \"Not Verified\", \n  annual_income_th = 59\n)\n\npredict(int_fit, new_borrower)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1  9.89\n```\n\n\n:::\n:::\n\n\n\n::: callout-note\nDifference in predicted value due to rounding the coefficients on the previous slide.\n:::\n\n## Confidence interval for $\\hat{\\mu}_y$\n\n::: question\nCalculate a 90% confidence interval for the **estimated mean interest rate** for borrowers with an debt-to-income ratio of 0.558, whose income is not verified, and who has an annual income of \\$59,000.\n:::\n\n<br>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(int_fit, new_borrower, type = \"conf_int\", level = 0.90)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  .pred_lower .pred_upper\n        <dbl>       <dbl>\n1        8.16        11.6\n```\n\n\n:::\n:::\n\n\n\n## Prediction interval for $\\hat{y}$\n\n::: question\nCalculate a 90% confidence interval for the **predicted interest rate** for an individual appllicant with an debt-to-income ratio of 0.558, whose income is not verified, and who has an annual income of \\$59,000.\n:::\n\n<br>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(int_fit, new_borrower, type = \"pred_int\", level = 0.90)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  .pred_lower .pred_upper\n        <dbl>       <dbl>\n1        2.18        17.6\n```\n\n\n:::\n:::\n\n\n\n## Cautions\n\n-   **Do not extrapolate!** Because there are multiple predictor variables, there is the potential to extrapolate in many directions\n-   The multiple regression model only shows **association, not causality**\n    -   To show causality, you must have a carefully designed experiment or carefully account for confounding variables in an observational study\n\n# Types of predictors\n\n## Interpreting results {.midi}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                           | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:------------------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)                    |   10.726|     1.507|     7.116|   0.000|    7.690|    13.762|\n|debt_to_income                 |    0.671|     0.676|     0.993|   0.326|   -0.690|     2.033|\n|verified_incomeSource Verified |    2.211|     1.399|     1.581|   0.121|   -0.606|     5.028|\n|verified_incomeVerified        |    6.880|     1.801|     3.820|   0.000|    3.253|    10.508|\n|annual_income_th               |   -0.021|     0.011|    -1.804|   0.078|   -0.043|     0.002|\n\n\n:::\n:::\n\n\n\n. . .\n\n<br>\n\n::: question\nDescribe the subset of borrowers who are expected to get an interest rate of 10.726% based on our model. Is this interpretation meaningful? Why or why not?\n:::\n\n# Mean-centered variables\n\n## Mean-centering\n\nIf we are interested in interpreting the intercept, we can **mean-center** the quantitative predictors in the model.\n\nWe can mean-center a quantitative predictor $X_j$ using the following:\n\n$$X_{j_{Cent}} = X_{j}- \\bar{X}_{j}$$\n\n. . .\n\nIf we mean-center all quantitative variables, then the intercept is interpreted as the expected value of the response variable when all quantitative variables are at their mean value.\n\n## Data manipulation 2: Mean-center numeric predictors\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan50 <- loan50 |>\n  mutate(\n    debt_inc_cent = debt_to_income - mean(debt_to_income), \n    annual_income_th_cent = annual_income_th - mean(annual_income_th)\n    )\n```\n:::\n\n\n\n## Visualize mean-centered predictors\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](09-mlr-old_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n## Using mean-centered variables in the model {.smaller}\n\n::: question\nHow do you expect the model to change if we use the `debt_inc_cent` and `annual_income_cent` in the model?\n:::\n\n. . .\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                           | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:------------------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)                    |    9.444|     0.977|     9.663|   0.000|    7.476|    11.413|\n|debt_inc_cent                  |    0.671|     0.676|     0.993|   0.326|   -0.690|     2.033|\n|verified_incomeSource Verified |    2.211|     1.399|     1.581|   0.121|   -0.606|     5.028|\n|verified_incomeVerified        |    6.880|     1.801|     3.820|   0.000|    3.253|    10.508|\n|annual_income_th_cent          |   -0.021|     0.011|    -1.804|   0.078|   -0.043|     0.002|\n\n\n:::\n:::\n\n\n\n## Original vs. mean-centered model {.small}\n\n::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                           | estimate|\n|:------------------------------|--------:|\n|(Intercept)                    |   10.726|\n|debt_to_income                 |    0.671|\n|verified_incomeSource Verified |    2.211|\n|verified_incomeVerified        |    6.880|\n|annual_income_th               |   -0.021|\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                           | estimate|\n|:------------------------------|--------:|\n|(Intercept)                    |    9.444|\n|debt_inc_cent                  |    0.671|\n|verified_incomeSource Verified |    2.211|\n|verified_incomeVerified        |    6.880|\n|annual_income_th_cent          |   -0.021|\n\n\n:::\n:::\n\n\n:::\n:::\n\n# Indicator variables\n\n## Indicator variables\n\n-   Suppose there is a categorical variable with $K$ categories (levels)\n\n-   We can make $K$ indicator variables - one indicator for each category\n\n-   An **indicator variable** takes values 1 or 0\n\n    -   1 if the observation belongs to that category\n    -   0 if the observation does not belong to that category\n\n## Data manipulation 3: Create indicator variables for `verified_income`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan50 <- loan50 |>\n  mutate(\n    not_verified = if_else(verified_income == \"Not Verified\", 1, 0),\n    source_verified = if_else(verified_income == \"Source Verified\", 1, 0),\n    verified = if_else(verified_income == \"Verified\", 1, 0)\n  )\n```\n:::\n\n\n\n. . .\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  verified_income not_verified source_verified verified\n  <fct>                  <dbl>           <dbl>    <dbl>\n1 Not Verified               1               0        0\n2 Verified                   0               0        1\n3 Source Verified            0               1        0\n```\n\n\n:::\n:::\n\n\n\n## Indicators in the model {.midi}\n\n-   We will use $K-1$ of the indicator variables in the model.\n-   The **baseline** is the category that doesn't have a term in the model.\n-   The coefficients of the indicator variables in the model are interpreted as the expected change in the response compared to the baseline, holding all other variables constant.\n-   This approach is also called **dummy coding**.\n\n. . .\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan50 |>\n  select(verified_income, source_verified, verified) |>\n  slice(1, 3, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  verified_income source_verified verified\n  <fct>                     <dbl>    <dbl>\n1 Not Verified                  0        0\n2 Verified                      0        1\n3 Source Verified               1        0\n```\n\n\n:::\n:::\n\n\n\n## Interpreting `verified_income` {.small}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 9.444 </td>\n   <td style=\"text-align:right;\"> 0.977 </td>\n   <td style=\"text-align:right;\"> 9.663 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 7.476 </td>\n   <td style=\"text-align:right;\"> 11.413 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> debt_inc_cent </td>\n   <td style=\"text-align:right;\"> 0.671 </td>\n   <td style=\"text-align:right;\"> 0.676 </td>\n   <td style=\"text-align:right;\"> 0.993 </td>\n   <td style=\"text-align:right;\"> 0.326 </td>\n   <td style=\"text-align:right;\"> -0.690 </td>\n   <td style=\"text-align:right;\"> 2.033 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(220, 229, 178, 255) !important;\"> verified_incomeSource Verified </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 2.211 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 1.399 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 1.581 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 0.121 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -0.606 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 5.028 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(220, 229, 178, 255) !important;\"> verified_incomeVerified </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 6.880 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 1.801 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 3.820 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 0.000 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 3.253 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 10.508 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> annual_income_th_cent </td>\n   <td style=\"text-align:right;\"> -0.021 </td>\n   <td style=\"text-align:right;\"> 0.011 </td>\n   <td style=\"text-align:right;\"> -1.804 </td>\n   <td style=\"text-align:right;\"> 0.078 </td>\n   <td style=\"text-align:right;\"> -0.043 </td>\n   <td style=\"text-align:right;\"> 0.002 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n. . .\n\n::: incremental\n-   The baseline category is `Not verified`.\n-   People with source verified income are expected to take a loan with an interest rate that is 2.211% higher, on average, than the rate on loans to those whose income is not verified, holding all else constant.\n:::\n\n. . .\n\n::: question\nInterpret the coefficient of `Verified` in the context of the data.\n:::\n\n# Interaction terms\n\n## Interaction terms\n\n-   Sometimes the relationship between a predictor variable and the response depends on the value of another predictor variable.\n-   This is an **interaction effect**.\n-   To account for this, we can include **interaction terms** in the model.\n\n## Interest rate vs. annual income\n\nThe lines are not parallel indicating there is an **interaction effect**. The slope of annual income differs based on the income verification.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: A numeric `legend.position` argument in `theme()` was deprecated in ggplot2\n3.5.0.\nℹ Please use the `legend.position.inside` argument of `theme()` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](09-mlr-old_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n## Interaction term in model {.smaller}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nint_cent_int_fit <- linear_reg() |>\n  set_engine(\"lm\") |>\n  fit(interest_rate ~ debt_inc_cent + verified_income + annual_income_th_cent + verified_income * annual_income_th_cent,\n      data = loan50)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 9.484 </td>\n   <td style=\"text-align:right;\"> 0.989 </td>\n   <td style=\"text-align:right;\"> 9.586 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> debt_inc_cent </td>\n   <td style=\"text-align:right;\"> 0.691 </td>\n   <td style=\"text-align:right;\"> 0.685 </td>\n   <td style=\"text-align:right;\"> 1.009 </td>\n   <td style=\"text-align:right;\"> 0.319 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> verified_incomeSource Verified </td>\n   <td style=\"text-align:right;\"> 2.157 </td>\n   <td style=\"text-align:right;\"> 1.418 </td>\n   <td style=\"text-align:right;\"> 1.522 </td>\n   <td style=\"text-align:right;\"> 0.135 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> verified_incomeVerified </td>\n   <td style=\"text-align:right;\"> 7.181 </td>\n   <td style=\"text-align:right;\"> 1.870 </td>\n   <td style=\"text-align:right;\"> 3.840 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> annual_income_th_cent </td>\n   <td style=\"text-align:right;\"> -0.007 </td>\n   <td style=\"text-align:right;\"> 0.020 </td>\n   <td style=\"text-align:right;\"> -0.341 </td>\n   <td style=\"text-align:right;\"> 0.735 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(220, 229, 178, 255) !important;\"> verified_incomeSource Verified:annual_income_th_cent </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -0.016 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 0.026 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -0.643 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 0.523 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(220, 229, 178, 255) !important;\"> verified_incomeVerified:annual_income_th_cent </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -0.032 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 0.033 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -0.979 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 0.333 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n## Interpreting interaction terms\n\n-   What the interaction means: The effect of annual income on the interest rate differs by -0.016 when the income is source verified compared to when it is not verified, holding all else constant.\n-   Interpreting `annual_income` for source verified: If the income is source verified, we expect the interest rate to decrease by 0.023% (-0.007 + -0.016) for each additional thousand dollars in annual income, holding all else constant.\n\n## Data manipulation 4: Create interaction variables {.smaller}\n\nDefining the interaction variable in the model formula as `verified_income * annual_income_th_cent` is an implicit data manipulation step as well\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 50\nColumns: 9\n$ `(Intercept)`                                          <dbl> 1, 1, 1, 1, 1, …\n$ debt_inc_cent                                          <dbl> -0.16511719, 0.…\n$ annual_income_th_cent                                  <dbl> -27.17, -26.17,…\n$ `verified_incomeNot Verified`                          <dbl> 1, 1, 0, 1, 1, …\n$ `verified_incomeSource Verified`                       <dbl> 0, 0, 0, 0, 0, …\n$ verified_incomeVerified                                <dbl> 0, 0, 1, 0, 0, …\n$ `annual_income_th_cent:verified_incomeNot Verified`    <dbl> -27.17, -26.17,…\n$ `annual_income_th_cent:verified_incomeSource Verified` <dbl> 0.00, 0.00, 0.0…\n$ `annual_income_th_cent:verified_incomeVerified`        <dbl> 0.00, 0.00, -11…\n```\n\n\n:::\n:::\n\n\n\n# Wrap up\n\n## Recap\n\n-   Introduced multiple linear regression\n\n-   Interpreted coefficients in the multiple linear regression model\n\n-   Calculated predictions and associated intervals for multiple linear regression models\n\n-   Mean-centered quantitative predictors\n\n-   Used indicator variables for categorical predictors\n\n-   Used interaction terms\n\n## Looking backward {.midi}\n\nData manipulation, with **dplyr** (from **tidyverse**):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan50 |>\n  select(interest_rate, annual_income, debt_to_income, verified_income) |>\n  mutate(\n    # 1. rescale income\n    annual_income_th = annual_income / 1000,\n    # 2. mean-center quantitative predictors\n    debt_inc_cent = debt_to_income - mean(debt_to_income),\n    annual_income_th_cent = annual_income_th - mean(annual_income_th),\n    # 3. create dummy variables for verified_income\n    source_verified = if_else(verified_income == \"Source Verified\", 1, 0),\n    verified = if_else(verified_income == \"Verified\", 1, 0),\n    # 4. create interaction variables\n    `annual_income_th_cent:verified_incomeSource Verified` = annual_income_th_cent * source_verified,\n    `annual_income_th_cent:verified_incomeVerified` = annual_income_th_cent * verified\n  )\n```\n:::\n\n\n\n## Looking forward (after Exam 01) {.midi}\n\n**Feature engineering**, with **recipes** (from **tidymodels**):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan_rec <- recipe( ~ ., data = loan50) |>\n  # 1. rescale income\n  step_mutate(annual_income_th = annual_income / 1000) |>\n  # 2. mean-center quantitative predictors\n  step_center(all_numeric_predictors()) |>\n  # 3. create dummy variables for verified_income\n  step_dummy(verified_income) |>\n  # 4. create interaction variables\n  step_interact(terms = ~ annual_income_th:verified_income)\n```\n:::\n\n\n\n## Recipe\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan_rec\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Recipe ──────────────────────────────────────────────────────────────────────\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Inputs \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNumber of variables by role\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\npredictor: 24\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Operations \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n• Variable mutation for: annual_income / 1000\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n• Centering for: all_numeric_predictors()\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n• Dummy variables from: verified_income\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n• Interactions with: annual_income_th:verified_income\n```\n\n\n:::\n:::\n",
    "supporting": [
      "09-mlr-old_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}